networks:
    my_app_db-dev:
        driver: bridge

services:
    my_app:
        container_name: my_app
        hostname: myapp
        image: some.repository.com/my_app_db:latest # need to start using image with already initialized database to speed up container startup
        command: [ "postgres", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "wal_level=logical" ] # would be nic eto get this into the image but for onw it must be enough
        ports:
            - 50032:5432
        networks:
            - my_app_db-dev
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1s
            timeout: 1s
            retries: 5
            start_period: 10s

    my_app_replica:
        container_name: my_app_replica
        image: some.repository.com/my_app_db:latest # need to start using image with already initialized database to speed up container startup
        command: [ "postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
        ports:
            - 50432:5432
        networks:
            - my_app_db-dev
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1s
            timeout: 1s
            retries: 5
            start_period: 10s
